version: '3.9'

services:
  mariadb:
    image: mariadb
    pull_policy: never
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql
      - /sys/fs/cgroup
    expose:
      - "3306"
    restart: on-failure
  
  wordpress:
    image: wordpress
    pull_policy: never
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    networks:
      - inception
    volumes:
      - wp:/var/www
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: on-failure

  nginx:
    image: nginx
    pull_policy: never
    build: ./requirements/nginx
    container_name: nginx
    networks:
      - inception
    volumes:
      - wp:/var/www
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: on-failure

  redis:
    image: redis
    pull_policy: never
    build: ./requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    volumes:
      - wp:/var/www
    expose:
      - "6379"
    depends_on:
      - wordpress
    restart: on-failure
  
  ftp:
    image: ftp
    pull_policy: never
    build: ./requirements/bonus/ftp
    container_name: ftp
    env_file: .env
    networks:
      - inception
    volumes:
      - wp:/var/www
      - /sys/fs/cgroup
    ports:
      - "21:21"
    depends_on:
      - wordpress
    restart: on-failure

  adminer:
    image: adminer
    pull_policy: never
    build: ./requirements/bonus/adminer
    container_name: adminer
    env_file: .env    
    networks:
      - inception
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    restart: on-failure
  
  node:
    image: node
    pull_policy: never
    build: ./requirements/bonus/node
    container_name: node
    ports:
      - "3000:3000"
    restart: on-failure

  minecraft:
    image: minecraft
    pull_policy: never
    build: ./requirements/bonus/minecraft
    container_name: minecraft
    ports:
      - "25565:25565"
    volumes:
      - mine:/server
    restart: on-failure


networks:
  inception:

volumes:
  db:
    driver_opts:
      type: none
      o: bind
      device: /home/juyojeon/data/mysql
  wp:
    driver_opts:
      type: none
      o: bind
      device: /home/juyojeon/data/www
  mine: